name: ğŸ–¼ï¸ Management

on:
  push:
    branches: [main]

env:
  IMAGE_NAME: scan
  REPO_NAME: equalifyapp

jobs:
  build-and-push:
    name: ğŸ—ï¸ and Push ğŸ³ Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        id: checkout
        uses: actions/checkout@v2

      - name: ğŸ—ï¸ ğŸ³ Image
        id: build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest
        env:
          DOCKER_BUILDKIT: 1
          BUILDKIT_INLINE_CACHE: 1
          DOCKER_USERNAME: ${{ github.actor }}
          DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
